# -*- coding: utf-8 -*-
"""api_server

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7BBrfL4Vm-eZoD0lI7MDJMFkN44FMMJ
"""

from fastapi import FastAPI
from pydantic import BaseModel
import joblib

app = FastAPI()

try:
    print("⏳ Loading model...")
    model = joblib.load("website_classifier_xgb.pkl")
    print("✅ Model loaded")
except Exception as e:
    print("❌ Error loading model:", e)
    model = None

class Features(BaseModel):
    Has_IP: int
    URL_Length: int
    Prefix_Suffix: int
    HTTPS_Token: int
    Has_At: int

@app.post("/predict")
def predict(features: Features):
    try:
        if model is None:
            return {"error": "Model not loaded"}

        input_data = [[
            features.Has_IP,
            features.URL_Length,
            features.Prefix_Suffix,
            features.HTTPS_Token,
            features.Has_At
        ]]
        prediction = model.predict(input_data)[0]
        return {"prediction": int(prediction)}

    except Exception as e:
        print("❌ Prediction error:", e)
        return {"error": str(e)}